/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface CeModal {
    'close': (e: any) => Promise<void>;
    'isOpen': boolean;
    'open': () => Promise<void>;
  }
}

declare global {


  interface HTMLCeModalElement extends Components.CeModal, HTMLStencilElement {}
  var HTMLCeModalElement: {
    prototype: HTMLCeModalElement;
    new (): HTMLCeModalElement;
  };
  interface HTMLElementTagNameMap {
    'ce-modal': HTMLCeModalElement;
  }
}

declare namespace LocalJSX {
  interface CeModal extends JSXBase.HTMLAttributes<HTMLCeModalElement> {
    'isOpen'?: boolean;
  }

  interface IntrinsicElements {
    'ce-modal': CeModal;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


